[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
verbosity = 3
optimizer = true
optimizer_runs = 100000

# See more config options https://github.com/gakonst/foundry/tree/master/config